version: '3.4'

services:
  reporthandler:
    # image: reporthandler
    build:
      context: ./backend/report_handler
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:3000
  posthandler:
    # image: posthandler
    build:
      context: ./backend/post_handler
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4002:7000
  userhandler:
    # image: userhandler
    build:
      context: ./backend/account_manager
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4001:5000
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './backend/data/db:/data/db'
  react:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80