version: '3.4'

services:
  userhandler:
    image: userhandler
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'